# Generated by Django 5.2.9 on 2025-12-14 08:46

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmotionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emotion', models.CharField(max_length=20, verbose_name='识别到的情感')),
                ('confidence', models.FloatField(verbose_name='置信度(%)')),
                ('image_name', models.CharField(max_length=255, verbose_name='图片名称')),
                ('image_path', models.CharField(max_length=500, verbose_name='图片路径')),
                ('created_at', models.DateTimeField(default=datetime.datetime.now, verbose_name='识别时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emotion_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '情感识别记录',
                'verbose_name_plural': '情感识别记录',
                'ordering': ['-created_at'],
            },
        ),
    ]
