# Generated by Django 5.2.9 on 2025-12-14 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emotion_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emotionrecord',
            name='image_path',
        ),
    ]
