# Generated by Django 5.2.9 on 2025-12-28 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emotion_app', '0003_userprofile'),
    ]

    operations = [
    ]
