# Generated by Django 5.2.9 on 2025-12-28 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emotion_app', '0004_auto_20251228_1601'),
    ]

    operations = [
        # 只删除不需要的字段
        migrations.RemoveField(
            model_name='userprofile',
            name='preferred_language',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='theme',
        ),
    ]