# Generated by Django 5.2.9 on 2025-12-28 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emotion_app', '0005_remove_theme_and_language'),
    ]

    operations = [
        # 只添加新的图片字段
        migrations.AddField(
            model_name='emotionrecord',
            name='image_data',
            field=models.BinaryField(blank=True, null=True, verbose_name='图片数据'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='emotionrecord',
            name='image_content_type',
            field=models.CharField(blank=True, max_length=100, verbose_name='图片MIME类型'),
            preserve_default=True,
        ),
    ]