# Generated by Django 5.2.9 on 2025-12-28 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emotion_app', '0006_add_image_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='recycle_bin_days',
            field=models.IntegerField(default=7, verbose_name='回收站保管天数', help_text='最高为7天'),
        ),
    ]
